version: '3'
name: admin-panel

services:
  database:
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    image: postgres:16
    volumes:
      - ./db_data:/db_data
    healthcheck:
       test: ["CMD-SHELL", "pg_isready -h localhost -U $$POSTGRES_USER -d $$POSTGRES_DB"]
       interval: 5s
       timeout: 10s
       retries: 5

  admin_panel:
    env_file:
      - path: ./.env
    build:
      dockerfile: build/movies_admin.Dockerfile
      context: .
    volumes:
      - ./static:/app/static
    depends_on:
      database:
        condition: service_healthy

  nginx:
    image: nginx:1.25.3
    volumes:
      - ./nginx_configs/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx_configs/configs:/etc/nginx/conf.d:ro
      - ./static:/data/static:ro
    depends_on:
      - database
      - admin_panel
    ports:
      - ${ADMIN_PORT}:${NGINX_PORT}
